# Generated by Django 3.1.2 on 2020-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('title', models.CharField(max_length=21, primary_key=True, serialize=False, unique=True)),
                ('cards', models.ManyToManyField(blank=True, related_name='cards', to='custom_deck.Card')),
            ],
        ),
    ]
